### ISSUE TITLE
Encoding issues in extracted text file

### ISSUE THREAD

**Issue by TomasHubelbauer** [xNyaDev/bfstool#4]
Hi, let me preface by saying this extractor is a fantastic effort - thank you!
I was familiar with https://github.com/synopia/bfs2pack (in fact, I was the guy who pestered Paul to put it on GitHub in 2015) but Rust is much nicer on the eyes for me, so browsing this code is actually enjoyable.

I have just discovered this repository and I might take a stab at fixing this myself later and contributing back, but I figured I'd open the issue already while I've discovered the issue:

I am browsing through the extracted contents of Flatout 2 BFS files, specifically `fo2a.bfs` (Steam [Deck] version - MD5 `04d2a94a91e9ecb18e81149a73842c25`) and I noticed some of the Finnish comments do not have the right decoding. For example in `global/dynamics/dynamic_objects.bed`:

```
-- bonus types
BONUSTYPE_ROADBLOCK = 1 	-- muovit�rp�t, renkaat, betoniporsaat, tynnyrit.
BONUSTYPE_FENCE 	= 2 	-- puu+metalli+jne -aidat, ja kaikki portit.
BONUSTYPE_MACHINERY	= 3 	-- mekaaniset koneet/autot. kamelit, henkil�autot, pittien liukuhihnat.
BONUSTYPE_SIGN 		= 4	-- kaikki mainoskyltit + liikennemerkit
BONUSTYPE_ACCESSORY	= 5	-- (FO2: lyhtypylv��t) ihmisen luomat yleiset roinat, useimmiten pienikokoiset esineet, jakoavaimet, kaasupullot, postilaatikot.
BONUSTYPE_NATURE 	= 6	-- tukit, polttopuut, luontoonliittyv�t asiat.
BONUSTYPE_STRUCTURE	= 7	-- kaikki tukirakenteet / isommat rakennelmat. katulamput, tikkaat, polet, rakennusten palaset jne.
BONUSTYPE_TIRE		= 8	-- renkaat.
BONUSTYPE_NITRO		= 9	-- esineet joista saa nitroa muttei rahaa, atm kivet.
```

It is possible this is a "problem" in the source files already as the comments aren't used at runtime anyway so it would not surprise me to learn they are misencoded in the original file stream already, but just in case that's not what's happening, here's the issue report in case that's something you want to take a look at!

**Comment by xNyaDev** [comment]
This is not a bfstool issue - your text editor simply opens them in the incorrect encoding. I am guessing your editor uses UTF-8 by default which will cause the issue. Using Notepad++ works fine and I do get the correct characters:
```
BONUSTYPE_ROADBLOCK = 1 	-- muovitörpöt, renkaat, betoniporsaat, tynnyrit.
```

Since you mentioned a Steam Deck, I guess you are using KDE's Kate as a text editor, which, based on my limited testing, should also detect the encoding fine. If it does not, you can manually change it in the bottom right corner. I believe the correct one is Western European -> ISO 8859-15, as that's what Kate autodetected for me.

**Comment by TomasHubelbauer** [comment]
Ah, should have thought of this! That was indeed the issue. Apologies and thanks again!
